### ISSUE TITLE
Nexgen: Can't install from git repo with pipenv

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#175]
Currently we install `nexgen` using `nexgen = {git = "https://github.com/dials/nexgen.git", editable = true}` in the Pipfile. This appears to be broken with the error:
```
INFO:pipenv.patched.notpip._internal.operations.prepare:Obtaining nexgen from git+https://github.com/dials/nexgen.git#egg=nexgen (from -r /tmp/pipenv0yz80b2nrequirements/pipenv-xuvi05r7-constraints.txt (line 9))
INFO:pipenv.patched.notpip._internal.vcs.versioncontrol:Updating ./.venv/src/nexgen clone
INFO:pipenv.patched.notpip._internal.utils.ui:Installing build dependencies: started
INFO:pipenv.patched.notpip._internal.utils.ui:Installing build dependencies: finished with status 'error'
ERROR:pip.subprocessor:Command errored out with exit status 2:
 command: /scratch/ffv81422/artemis/python-artemis/.venv/bin/python /dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ed2zhsc9/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --pre -- 'setuptools >= 40.6.0' wheel
     cwd: None
Complete output (37 lines):
ERROR: Exception:
Traceback (most recent call last):
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 182, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 286, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 934, in find_requirement
    best_candidate_result = self.find_best_candidate(
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 917, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 861, in find_all_candidates
    package_links = self.process_project_url(
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 833, in process_project_url
    package_links = self.evaluate_links(
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 815, in evaluate_links
    candidate = self.get_install_candidate(link_evaluator, link)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 793, in get_install_candidate
    is_candidate, result = link_evaluator.evaluate_link(link)
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 201, in evaluate_link
    supported_tags = self._target_python.get_tags()
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/models/target_python.py", line 99, in get_tags
    tags = get_supported(
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/pep425tags.py", line 144, in get_supported
    supported.extend(
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/packaging/tags.py", line 242, in cpython_tags
    platforms = list(platforms or _platform_tags())
  File "/dls_sw/prod/python3/RHEL7-x86_64/pipenv/2021.5.29/lightweight-venv/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/packaging/tags.py", line 638, in _linux_platforms
    linux = _normalize_string(distutils.util.get_platform())
AttributeError: module 'distutils' has no attribute 'util'
```

As a workaround we can remove nexgen from our dependencies in this way and run `pipenv run pip install git+https://github.com/dials/nexgen.git` to install it after everything else is installed. This hopefully isn't a long term issue as we will be moving to a release version of `nexgen`

**Comment by DominicOram** [comment]
FYI, @noemifrisina. I'm not sure what the underlying cause of this is, I'm going to run with the workaround for testing in the short-term but would be good to get a nexgen release once we're running Artemis on the beamline that we can pin too and hopefully will not have this issue

**Comment by DominicOram** [comment]
Ok, issue with the workaround above is that it will break all the CI as it doesn't then know that `nexgen` is a dependency. I've found that it does work with the latest version of `pipenv`, just not the one DLS has by default. Therefore new workaround is:
* Install just the venv: `pipenv --python 3.10`
* Install the latest `pipenv` into that venv: `pipenv run pip install pipenv`
* Install all the dependencies using that new `pipenv`: `pipenv run pipenv install --dev`

**Comment by DominicOram** [comment]
Closing this as we're now using an actual release of `nexgen` and hopefully will be going forward so this is less of an issue
