### ISSUE TITLE
Ophyd wait timeout on filewriters

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#395]
https://ispyb.diamond.ac.uk/dc/visit/cm31105-5/dcg/8293826 did not get any results. After discussion with analysis this seems to be because we did not trigger an end in zocalo.

## Acceptance Criteria
* The root cause of the issue is discovered
* A fix is implemented

**Comment by DominicOram** [comment]
Root issue here was the following:
```
Traceback (most recent call last):
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 575, in contingency_wrapper
    ret = yield from plan
  File "/dls_sw/i03/software/artemis/src/artemis/fast_grid_scan_plan.py", line 96, in run_gridscan
    yield from do_fgs()
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 528, in finalize_wrapper
    yield from ensure_generator(final_plan_instance)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 946, in unstage_devices
    yield Msg('unstage', d)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1583, in _run
    new_response = await coro(msg)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 2352, in _unstage
    result = obj.unstage()
  File "/dls_sw/i03/software/artemis/src/artemis/devices/eiger.py", line 76, in unstage
    self.odin.nodes.wait_for_filewriters_to_finish()
  File "/dls_sw/i03/software/artemis/src/artemis/devices/eiger_odin.py", line 63, in wait_for_filewriters_to_finish
    await_value(node_pv.writing, 0).wait(30)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 412, in wait
    raise WaitTimeoutError("Status has not completed yet.")
ophyd.utils.errors.WaitTimeoutError: Status has not completed yet.
```

This didn't get passed to GDA as the GDA timeout for Artemis < the timeout for the filewriters to finish. We should increase the GDA timeout to significantly larger than any timeouts Artemis could be waiting on.

I can't find the odin logs in graylog right now, have asked @GDYendell about that. It may be worth if this happens again getting Artemis to check the error messages from odin and putting these into the exception too

**Comment by DominicOram** [comment]
After https://github.com/DiamondLightSource/python-artemis/pull/381 we should always be sending the end message to zocalo, even if we fail

**Comment by DominicOram** [comment]
I'm not 100% sure of what happened here but I think it could be a very rare race condition. It looked like we created the subscription on the file writers finishing at almost the exact same time as the PV transitioned to finished. It looks like the subscription does do a check on the value when it is first created so I can't see where this would cause an issue but I'm going to move the creation of the subscription earlier just in case.
