### ISSUE TITLE
Full OAV image fails to write valid nexus file

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#397]
When running against an empty OAV image (i.e. a grid that covers the whole span of the image https://ispyb.diamond.ac.uk/dc/visit/cm31105-5/dcg/8303570) we got the following issue in analysis:
```
2022-11-25 13:03:44.319000+00:00
                    _id: 976acc00-6cc1-11ed-999c-1866dafae8e4
               facility: dlstbx.services.filewatcher
                   file: /dials/modules/dlstbx/src/dlstbx/services/filewatcher.py
           full_message: Traceback (most recent call last):
                       |   File "/dials/modules/dlstbx/src/dlstbx/services/filewatcher.py", line 710, in watch_files_swmr
                       |     dataset_files, file_map = h5check.get_real_frames(f, d)
                       |   File "/dials/modules/dlstbx/src/dlstbx/swmr/h5check.py", line 55, in get_real_frames
                       |     frames = vspace.get_regular_hyperslab()[3][0]
                       |   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
                       |   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
                       |   File "h5py/h5s.pyx", line 615, in h5py.h5s.SpaceID.get_regular_hyperslab
                       | ValueError: Not a hyperslab selection (not a hyperslab selection)
               function: watch_files_swmr
                  level: 3
             level_name: ERROR
                   line: 714
                message: Error reading /dls/i03/data/2022/cm31105-5/xraycentring/manual/xrc_46.nxs
                    pid: 389
           process_name: workflows-service
              recipe_ID: 7971ba2c-f96c-469f-8351-94b5494cc761
                 source: zocalo-filewatcher-7df49f648d-lfhx2
            thread_name: MainThread
              timestamp: 2022-11-25T13:03:44.319Z
workflows_container_image: gcr.io/diamond-privreg/scisoft/dlstbx:b41f992d
workflows_container_node: cs04r-sc-cloud-04.diamond.ac.uk
       workflows_dlstbx: dlstbx 0.3240-gb41f992d
         workflows_host: zocalo-filewatcher-7df49f648d-lfhx2.1
      workflows_mem-uss: 29057024
      workflows_service: DLS Filewatcher
 workflows_serviceclass: DLSFileWatcher
       workflows_status: 4
   workflows_statustext: processing
  workflows_utilization: {"2":0.9917,"4":0.0083}
    workflows_workflows: 2.26
       workflows_zocalo: 0.26.0
```

## Acceptance Criteria
* Fix the above

**Comment by DominicOram** [comment]
Closing this as the underlying cause is https://github.com/DiamondLightSource/python-artemis/issues/408
