### ISSUE TITLE
Reading SCAN_INVALID PV twice with S03 causes exception

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#462]
in `wait_for_fgs_valid()`:

```python
def wait_for_fgs_valid(fgs_motors: FastGridScan, timeout=0.5):
    artemis.log.LOGGER.info("Waiting for valid fgs_params")
    SLEEP_PER_CHECK = 0.1
    times_to_check = int(timeout / SLEEP_PER_CHECK)
    for _ in range(times_to_check):
        scan_invalid = yield from bps.rd(fgs_motors.scan_invalid)
        pos_counter = yield from bps.rd(fgs_motors.position_counter)
        if not scan_invalid and pos_counter == 0:
            return
        yield from bps.sleep(SLEEP_PER_CHECK)
    raise WarningException(f"Scan parameters invalid after {timeout} seconds")
```

If timeout is set to anything > 0.1, i.e., the bps.rd happens more than once, we get the following exception:

```
Traceback (most recent call last):
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1523, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/scratch/ziq44869/Development/python-artemis/src/artemis/fast_grid_scan_plan.py", line 152, in run_gridscan_and_move
    yield from gridscan_with_subscriptions(fgs_composite, eiger, parameters)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 382, in subs_wrapper
    return (yield from finalize_wrapper(_inner_plan(),
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 380, in _inner_plan
    return (yield from plan)
  File "/scratch/ziq44869/Development/python-artemis/src/artemis/fast_grid_scan_plan.py", line 149, in gridscan_with_subscriptions
    yield from run_gridscan(fgs_composite, detector, params)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 325, in run_wrapper
    yield from contingency_wrapper(plan,
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 575, in contingency_wrapper
    ret = yield from plan
  File "/scratch/ziq44869/Development/python-artemis/src/artemis/fast_grid_scan_plan.py", line 117, in run_gridscan
    yield from wait_for_fgs_valid(fgs_motors)
  File "/scratch/ziq44869/Development/python-artemis/src/artemis/fast_grid_scan_plan.py", line 65, in wait_for_fgs_valid
    scan_invalid = yield from bps.rd(fgs_motors.scan_invalid)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/plan_stubs.py", line 371, in rd
    ret = yield from read(obj)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/plan_stubs.py", line 96, in read
    return (yield Msg('read', obj))
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1583, in _run
    new_response = await coro(msg)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1848, in _read
    await current_run.read(msg, ret)
  File "/scratch/ziq44869/Development/python-artemis/.venv/lib/python3.10/site-packages/bluesky/bundlers.py", line 201, in read
    raise ValueError(
ValueError: Data keys (field names) from EpicsSignalRO(read_pv='BL03S-MO-SGON-01:FGS:SCAN_INVALID', name='fgs_fast_grid_scan_scan_invalid', parent='fgs_fast_grid_scan', value=1, timestamp=1671453737.09808, auto_monitor=False, string=False) collide with those from EpicsSignalRO(read_pv='BL03S-MO-SGON-01:FGS:SCAN_INVALID', name='fgs_fast_grid_scan_scan_invalid', parent='fgs_fast_grid_scan', value=1, timestamp=1671453737.09808, auto_monitor=False, string=False). The colliding keys are {'fgs_fast_grid_scan_scan_invalid'}

```

**Comment by dperl-dls** [comment]
possibly we see this error with S03 and not on the beamline because the timestamp for the readings is identical

**Comment by dperl-dls** [comment]
we see the same error for POS_COUNTER if the read of scan_invalid is commented out
