### ISSUE TITLE
Log *which* status is not complete

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#480]
`[2023-01-21 01:05:06,649] Artemis eiger INFO: Waiting on stale parameters to go low
[2023-01-21 01:05:07,616] Artemis eiger INFO: Setting aquire
[2023-01-21 01:05:14,618] ophyd status WARNING: DeviceStatus(device=fgs_fast_grid_scan, done=False, success=False) has timed out
[2023-01-21 01:05:44,887] Artemis nexus_callback INFO: Updating Nexus file timestamps.
[2023-01-21 01:05:44,901] Artemis store_in_ispyb INFO: End ispyb deposition with status ‘fail’ and reason ‘Status has not completed yet.’.`

When something in an ophyd device times out we log the exception (last line of above). But there are many statuses which could not be completed, so we should report which status it is.

**Comment by dperl-dls** [comment]
we do actually get the whole stack trace in graylog:

`message
[2023-01-21 01:06:15,811] bluesky run_engine ERROR: Failed to unstage EigerDetector(prefix='BL03I-EA-EIGER-01:', name='eiger', read_attrs=['cam', 'odin', 'odin.fan', 'odin.fan.on', 'odin.fan.connected', 'odin.fan.ready', 'odin.fan.zmq_addr', 'odin.fan.zmq_port', 'odin.fan.state', 'odin.fan.frames_sent', 'odin.fan.series', 'odin.fan.offset', 'odin.fan.forward_stream', 'odin.file_writer', 'odin.meta', 'odin.meta.initialised', 'odin.meta.ready', 'odin.meta.file_name', 'odin.nodes', 'odin.nodes.node_0', 'odin.nodes.node_0.writing', 'odin.nodes.node_0.frames_dropped', 'odin.nodes.node_0.frames_timed_out', 'odin.nodes.node_0.error_status', 'odin.nodes.node_0.fp_initialised', 'odin.nodes.node_0.fr_initialised', 'odin.nodes.node_0.clear_errors', 'odin.nodes.node_0.error_message', 'odin.nodes.node_1', 'odin.nodes.node_1.writing', 'odin.nodes.node_1.frames_dropped', 'odin.nodes.node_1.frames_timed_out', 'odin.nodes.node_1.error_status', 'odin.nodes.node_1.fp_initialised', 'odin.nodes.node_1.fr_initialised', 'odin.nodes.node_1.clear_errors', 'odin.nodes.node_1.error_message', 'odin.nodes.node_2', 'odin.nodes.node_2.writing', 'odin.nodes.node_2.frames_dropped', 'odin.nodes.node_2.frames_timed_out', 'odin.nodes.node_2.error_status', 'odin.nodes.node_2.fp_initialised', 'odin.nodes.node_2.fr_initialised', 'odin.nodes.node_2.clear_errors', 'odin.nodes.node_2.error_message', 'odin.nodes.node_3', 'odin.nodes.node_3.writing', 'odin.nodes.node_3.frames_dropped', 'odin.nodes.node_3.frames_timed_out', 'odin.nodes.node_3.error_status', 'odin.nodes.node_3.fp_initialised', 'odin.nodes.node_3.fr_initialised', 'odin.nodes.node_3.clear_errors', 'odin.nodes.node_3.error_message', 'stale_params', 'bit_depth'], configuration_attrs=['cam', 'cam.acquire_period', 'cam.acquire_time', 'cam.image_mode', 'cam.manufacturer', 'cam.model', 'cam.num_exposures', 'cam.num_images', 'cam.shutter_mode', 'cam.trigger_mode', 'cam.num_triggers', 'cam.beam_center_x', 'cam.beam_center_y', 'cam.wavelength', 'cam.det_distance', 'cam.threshold_energy', 'cam.photon_energy', 'cam.manual_trigger', 'cam.special_trigger_button', 'odin', 'odin.fan', 'odin.file_writer', 'odin.meta', 'odin.nodes', 'odin.nodes.node_0', 'odin.nodes.node_1', 'odin.nodes.node_2', 'odin.nodes.node_3']).
Traceback (most recent call last):
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 950, in inner
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/src/artemis/fast_grid_scan_plan.py", line 119, in do_fgs
    yield from bps.complete(fgs_motors, wait=True)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/plan_stubs.py", line 625, in complete
    yield from _wait(group=group)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/plan_stubs.py", line 468, in wait
    return (yield Msg('wait', None, group=group))
bluesky.utils.FailedStatus: DeviceStatus(device=fgs_fast_grid_scan, done=True, success=False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1663, in _run
    raise err
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1523, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/dls_sw/i03/software/artemis/src/artemis/fast_grid_scan_plan.py", line 152, in run_gridscan_and_move
    yield from gridscan_with_subscriptions(fgs_composite, eiger, parameters)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 382, in subs_wrapper
    return (yield from finalize_wrapper(_inner_plan(),
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 380, in _inner_plan
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/src/artemis/fast_grid_scan_plan.py", line 149, in gridscan_with_subscriptions
    yield from run_gridscan(fgs_composite, detector, params)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 325, in run_wrapper
    yield from contingency_wrapper(plan,
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 575, in contingency_wrapper
    ret = yield from plan
  File "/dls_sw/i03/software/artemis/src/artemis/fast_grid_scan_plan.py", line 122, in run_gridscan
    yield from do_fgs()
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/utils/__init__.py", line 1147, in dec_inner
    return (yield from plan)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/preprocessors.py", line 528, in finalize_wrapper
    yield from ensure_generator(final_plan_instance)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1583, in _run
    new_response = await coro(msg)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 2352, in _unstage
    result = obj.unstage()
  File "/dls_sw/i03/software/artemis/src/artemis/devices/eiger.py", line 78, in unstage
    self.filewriters_finished.wait(30)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 412, in wait
    raise WaitTimeoutError("Status has not completed yet.")
ophyd.utils.errors.WaitTimeoutError: Status has not completed yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1682, in _run
    obj.unstage()
  File "/dls_sw/i03/software/artemis/src/artemis/devices/eiger.py", line 78, in unstage
    self.filewriters_finished.wait(30)
  File "/dls_sw/i03/software/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 412, in wait
    raise WaitTimeoutError("Status has not completed yet.")
ophyd.utils.errors.WaitTimeoutError: Status has not completed yet.`

**Comment by dperl-dls** [comment]
Pull request to ophyd has been made to improve this: https://github.com/bluesky/ophyd/pull/1088
If that is accepted we will still have to change our code and avoid using `StatusBase` and rather use `Status` (or another subclass which adds specific info to __repr__) and add an `obj` on init
