### ISSUE TITLE
Issues with v5.0.0 (Part 1)

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#759]
1) Zebra Arming Device needs an empty string prefix
1) The changes made to the detector motion in https://github.com/DiamondLightSource/dodal/commit/c4269b98a8c9cc7f6cc6a5a336442950f38b5c29 break i03 (not that I'm not even sure they look right for i24 either)
1) PinTipDetect Device needs an empty string prefix, doesn't need an `__init__`
1) Zoom prefixes (`BL03I-EA-OAV-01:`) are different to OAV prefixes (`BL03I-DI-OAV-01`)
1) Full grid scan is still sending subscriptions to fast grid scan, doesn't need it
1) General - if there's an exception whilst grid detect we need to disarm det
1) Issue converting `upper_left`:
```[2023-06-27 16:00:51,033] Artemis __main__ ERROR: Exception on running plan
Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/src/artemis/__main__.py", line 118, in wait_on_queue
    self.RE(command.experiment(command.parameters))
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 899, in __call__
    plan_return = self._resume_task(init_func=_build_task)
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1038, in _resume_task
    raise exc
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1668, in _run
    raise err
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 1528, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/src/artemis/experiment_plans/full_grid_scan.py", line 139, in detect_grid_and_do_gridscan
    yield from fgs_get_plan(parameters)
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/src/artemis/experiment_plans/fast_grid_scan_plan.py", line 313, in get_plan
    "hyperion_internal_parameters": parameters.json(),
  File "pydantic/main.py", line 491, in pydantic.main.BaseModel.json
  File "pydantic/main.py", line 868, in _iter
  File "pydantic/main.py", line 743, in pydantic.main.BaseModel._get_value
  File "pydantic/main.py", line 449, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 868, in _iter
  File "pydantic/main.py", line 743, in pydantic.main.BaseModel._get_value
  File "/dls_sw/i03/software/bluesky/artemis_v5.0.0/artemis/src/artemis/external_interaction/ispyb/ispyb_dataclass.py", line 47, in dict
    as_dict["upper_left"] = as_dict["upper_left"].tolist()
AttributeError: 'list' object has no attribute 'tolist'```

**Comment by DominicOram** [comment]
Tests were run using the `i03_live_art_v5` branch on GDA and the latest artemis version installed in `dls_sw/i03/software/bluesky`

Short term fixes will be in an incoming PR, long term question of how do we make sure we catch similar problems offline:
* 1, 2, 3 and 4 would have been caught by putting (https://github.com/DiamondLightSource/dodal/issues/3) in CI
* 5 and 7 are poor coverage of tests in `full_grid_scan`, having a system test for full grid scan would have caught it but more unit tests would have too
* 6 I think is just a general developer oversight, not thinking about what happens if something goes wrong

**Comment by DominicOram** [comment]
1-4 fixed in https://github.com/DiamondLightSource/dodal/pull/106
5 spun into https://github.com/DiamondLightSource/python-artemis/issues/765
6-7 fixed in https://github.com/DiamondLightSource/python-artemis/pull/766
