### ISSUE TITLE
Issues with v5 (part 2)

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#781]
* `GridAxis` on the `GridParams` needed reinitialising e.g. hacky code:
```python
    out_parameters.x_axis = GridAxis(
        out_parameters.x_start, out_parameters.x_step_size, out_parameters.x_steps
    )
    out_parameters.y_axis = GridAxis(
        out_parameters.y1_start, out_parameters.y_step_size, out_parameters.y_steps
    )
    out_parameters.z_axis = GridAxis(
        out_parameters.z2_start, out_parameters.z_step_size, out_parameters.z_steps
    )
```
* Snapshots not changing e.g. still using the same snapshot as previous sample. Issue was the `OavSnapshotCallback` is holding state as class variables and so keeping it between runs
* Error in logs, doesn't seem to be causing issues:
```
[2023-07-06 15:44:04,951] ophyd status ERROR: An error was raised on a background thread while running the callback <function PinTipDetect.trigger.<locals>.set_to_default_and_finish at 0x7f9e446bf130>(Status(obj=PinTipDetect(prefix='BL03I-DI-OAV-01:MXSC:', name='oav_mxsc_pin_tip', parent='oav_mxsc', read_attrs=['tip_x', 'tip_y', 'triggered_tip', 'validity_timeout'], configuration_attrs=[]), done=True, success=False)).
Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/dodal/src/dodal/devices/areadetector/plugins/MXSC.py", line 35, in set_to_default_and_finish
    subscription_status.set_finished()
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 742, in set_finished
    super().set_finished()
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 337, in set_finished
    raise InvalidState(
ophyd.utils.errors.InvalidState: Either set_finished() or set_exception() has already been called on SubscriptionStatus(device=oav_mxsc_pin_tip_tip_x, done=True, success=True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 268, in _run_callbacks
    cb(self)
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/dodal/src/dodal/devices/areadetector/plugins/MXSC.py", line 37, in set_to_default_and_finish
    subscription_status.set_exception(e)
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 317, in set_exception
    raise InvalidState(
ophyd.utils.errors.InvalidState: Either set_finished() or set_exception() has already been called on SubscriptionStatus(device=oav_mxsc_pin_tip_tip_x, done=True, success=True)
```

**Comment by DominicOram** [comment]
Final point addressed in https://github.com/DiamondLightSource/python-artemis/issues/789
