### ISSUE TITLE
Investigate and reduce status timeout errors

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#789]
We're getting a lot of `[2023-07-12 13:50:25,579] ophyd status WARNING: Status(obj=PinTipDetect(prefix='BL03I-DI-OAV-01:MXSC:', name='oav_mxsc_pin_tip', parent='oav_mxsc', read_attrs=['tip_x', 'tip_y', 'triggered_tip', 'validity_timeout'], configuration_attrs=[]), done=False, success=False) has timed out` errors in the logs, they don't seem to be causing issues but they're making diagnosing genuine issues hard, we should work out their cause and stop them. Following this error message we then get:
```
Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/dodal/src/dodal/devices/areadetector/plugins/MXSC.py", line 35, in set_to_default_and_finish
    subscription_status.set_finished()
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 742, in set_finished
    super().set_finished()
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 337, in set_finished
    raise InvalidState(
ophyd.utils.errors.InvalidState: Either set_finished() or set_exception() has already been called on SubscriptionStatus(device=oav_mxsc_pin_tip_tip_x, done=True, success=True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 268, in _run_callbacks
    cb(self)
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/dodal/src/dodal/devices/areadetector/plugins/MXSC.py", line 37, in set_to_default_and_finish
    subscription_status.set_exception(e)
  File "/dls_sw/i03/software/bluesky/artemis_v5.1.0/artemis/.venv/lib/python3.10/site-packages/ophyd/status.py", line 317, in set_exception
    raise InvalidState(
ophyd.utils.errors.InvalidState: Either set_finished() or set_exception() has already been called on SubscriptionStatus(device=oav_mxsc_pin_tip_tip_x, done=True, success=True)
```

**Comment by DominicOram** [comment]
Testing on beamline found a couple of issues:
* Timeout status wasn't getting cleaned up on the pin being found
* Running the subscription status callback immediately causes race conditions as the initial run and the quickly updating PV can clash

Fixed with:
```python
    def trigger(self) -> Status:
        subscription_status = SubscriptionStatus(
            self.tip_x, self.update_tip_if_valid, run=False
        )  # Do not run on creation as the PV updates often and can cause race conditions

        def set_to_default_and_finish(status: Status):
            try:
                if not status.success:
                    LOGGER.warn(
                        f"Waiting for valid tip timed out, setting to {self.INVALID_POSITION}"
                    )
                    self.triggered_tip.set(self.INVALID_POSITION)
                    subscription_status.set_finished()
            except Exception as e:
                LOGGER.error(f"Pin tip timeout failed with {e}")
                subscription_status.set_exception(e)

        # We use a separate status for measuring the timeout as we don't want an error
        # on the returned status
        validity_status = Status(self, timeout=self.validity_timeout.get())
        validity_status.add_callback(set_to_default_and_finish)
        subscription_status.add_callback(lambda: validity_status.set_finished())

        return subscription_status
```
